'use strict';
// Repository coherence checks (npm run validate). Exit code 0 is the only pass signal.
//  1. Every registered route has handler.js, a generated index.js and a function.json whose
//     methods/route match the registry; the handler exports exactly the registered methods.
//  2. No function directory exists outside the registry.
//  3. staticwebapp.config.json: Google-only auth, rolesSource, fail-closed /api/* catch-all last,
//     anonymous access only on the allowlist, CSP without unsafe-inline.
//  4. version.json equals api/version.json and both package.json versions.
//  5. schemaVersion is only assigned in api/_shared/schema.js.
//  6. The API has no forbidden patterns: eval, new Function, child_process, innerHTML.
//  7. .gitignore still covers the private-data and credential patterns.
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const errors = [];
const fail = (msg) => errors.push(msg);
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const json = (rel) => JSON.parse(read(rel));

const { ROUTES } = require(path.join(ROOT, 'api/_shared/routes.js'));

for (const [name, def] of Object.entries(ROUTES)) {
  const dir = path.join(ROOT, 'api', name);
  for (const file of ['handler.js', 'index.js', 'function.json']) {
    if (!fs.existsSync(path.join(dir, file))) fail(`api/${name}/${file} is missing`);
  }
  if (!fs.existsSync(path.join(dir, 'function.json'))) continue;
  const fn = json(`api/${name}/function.json`);
  const trigger = (fn.bindings || []).find((b) => b.type === 'httpTrigger');
  if (!trigger || trigger.route !== name || trigger.authLevel !== 'anonymous') fail(`api/${name}/function.json route/auth mismatch`);
  const methods = (trigger && trigger.methods || []).map((m) => m.toUpperCase()).sort();
  if (JSON.stringify(methods) !== JSON.stringify([...def.methods].sort())) fail(`api/${name}/function.json methods differ from registry`);
  const handler = require(path.join(dir, 'handler.js'));
  const exported = Object.keys(handler).filter((k) => /^[A-Z]+$/.test(k)).sort();
  if (JSON.stringify(exported) !== JSON.stringify([...def.methods].sort())) fail(`api/${name}/handler.js exports ${exported} but registry has ${def.methods}`);
  if (!read(`api/${name}/index.js`).includes('Generated by scripts/generate-functions.cjs')) fail(`api/${name}/index.js is not generated`);
}
for (const entry of fs.readdirSync(path.join(ROOT, 'api'), { withFileTypes: true })) {
  if (entry.isDirectory() && fs.existsSync(path.join(ROOT, 'api', entry.name, 'function.json')) && !ROUTES[entry.name]) fail(`api/${entry.name} is not in the route registry`);
}

const swa = json('staticwebapp.config.json');
const providers = Object.keys((swa.auth && swa.auth.identityProviders) || {});
if (JSON.stringify(providers) !== '["google"]') fail('staticwebapp.config.json must configure Google as the only identity provider');
if (!swa.auth || swa.auth.rolesSource !== '/api/roles') fail('rolesSource must be /api/roles');
const routes = swa.routes || [];
const last = routes[routes.length - 1];
if (!last || last.route !== '/api/*' || JSON.stringify(last.allowedRoles) !== '["authenticated"]') fail('the last route must be the fail-closed /api/* authenticated catch-all');
const ANON_ALLOWED = new Set(['/api/roles', '/api/site-settings']);
for (const r of routes) {
  if ((r.allowedRoles || []).includes('anonymous') && !ANON_ALLOWED.has(r.route)) fail(`anonymous access is not allowed on ${r.route}`);
  if (r.route === '/api/site-settings' && (r.methods || []).includes('PUT') && (r.allowedRoles || []).includes('anonymous')) fail('site-settings PUT must not be anonymous');
}
const csp = (swa.globalHeaders || {})['Content-Security-Policy'] || '';
if (!csp || /unsafe-inline|unsafe-eval|unsafe-hashes/.test(csp)) fail('CSP must exist and must not allow unsafe-inline/eval/hashes');
if ((swa.globalHeaders || {})['Cache-Control']) fail('do not set a global Cache-Control; API responses set no-store themselves');

const v = json('version.json');
if (JSON.stringify(v) !== JSON.stringify(json('api/version.json'))) fail('version.json and api/version.json differ');
if (json('package.json').version !== v.version || json('api/package.json').version !== v.version) fail('package.json versions differ from version.json');

const walk = (dir, out = []) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === 'test') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else if (p.endsWith('.js')) out.push(p);
  }
  return out;
};
for (const file of walk(path.join(ROOT, 'api'))) {
  const rel = path.relative(ROOT, file).replace(/\\/g, '/');
  const text = fs.readFileSync(file, 'utf8');
  if (rel !== 'api/_shared/schema.js' && /schemaVersion\s*[:=]\s*\d/.test(text)) fail(`${rel} assigns a schemaVersion literal; use schema.stampDocument`);
  if (/\beval\s*\(|new Function\s*\(|require\(['"]node:child_process['"]\)|require\(['"]child_process['"]\)|innerHTML/.test(text)) fail(`${rel} uses a forbidden API`);
}

// 8. Frontend: no inline script/style in index.html, fetch only in app/js/core/api.js, no
//    innerHTML/outerHTML/insertAdjacentHTML/document.write/eval, no style attributes (the CSP
//    forbids them; use el(..., { vars })), and every relative import resolves to a real file.
const indexHtml = read('index.html');
if (/<script(?![^>]*\bsrc=)[^>]*>/i.test(indexHtml) || /<style[\s>]/i.test(indexHtml) || /\sstyle\s*=/i.test(indexHtml) || /\son[a-z]+\s*=/i.test(indexHtml)) {
  fail('index.html must not contain inline script, style or event-handler attributes');
}
const appFiles = [];
const walkApp = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { if (e.name !== 'test') walkApp(p); } else if (p.endsWith('.js')) appFiles.push(p);
  }
};
if (fs.existsSync(path.join(ROOT, 'app/js'))) walkApp(path.join(ROOT, 'app/js'));
for (const file of appFiles) {
  const rel = path.relative(ROOT, file).replace(/\\/g, '/');
  const text = fs.readFileSync(file, 'utf8');
  if (rel !== 'app/js/core/api.js' && /\bfetch\s*\(/.test(text)) fail(`${rel} calls fetch; only app/js/core/api.js may`);
  if (rel.startsWith('app/js/vendor/')) {
    // A registered, generated bundle (rule 10) cannot be rewritten to satisfy the proxies below —
    // ProseMirror parses pasted HTML into an inert document and positions its cursor through the
    // CSSOM. It is held to the mechanisms that actually matter: no document.write, eval or new
    // Function, and no style ATTRIBUTE (which style-src 'self' blocks).
    if (/document\.write|\beval\s*\(|new Function\s*\(|setAttribute\(\s*['"]style['"]/.test(text)) fail(`${rel} (vendored) uses document.write, eval, new Function or a style attribute`);
  } else {
    if (/\.(innerHTML|outerHTML)\s*=|insertAdjacentHTML|document\.write|\beval\s*\(|new Function\s*\(/.test(text)) fail(`${rel} uses an HTML-injection or eval API`);
    if (/setAttribute\(\s*['"]style['"]|\.style\.cssText|\bstyle\s*:\s*['"`]/.test(text)) fail(`${rel} sets an inline style; use el(..., { vars })`);
  }
  if (rel.startsWith('app/js/core/') && /\b(document|window)\./.test(text) && !/globalThis/.test(text)) fail(`${rel} touches the DOM; core modules must stay DOM-free`);
  for (const m of text.matchAll(/^\s*import\s[^'"]*['"](\.[^'"]+)['"]/gm)) {
    if (!fs.existsSync(path.resolve(path.dirname(file), m[1]))) fail(`${rel} imports missing ${m[1]}`);
  }
}

// 9. No raw control or invisible characters in source, data, style or documentation files: they
//    make Git treat a file as binary (no reviewable diff) and hide what a regular expression or
//    string really contains. Write them as escapes instead. The pattern is built from char codes
//    so this file itself stays plain text.
const RAW_CHARS = new RegExp(`[${[[0, 8], [11, 12], [14, 31], [127, 127]].map(([a, b]) => (a === b ? String.fromCharCode(a) : `${String.fromCharCode(a)}-${String.fromCharCode(b)}`)).join('')}${String.fromCharCode(0xfeff, 0xa0, 0x2028, 0x2029, 0x200b)}]`);
const TEXT_FILE = /\.(js|cjs|mjs|json|css|html|md|ps1|toml|ya?ml|txt)$/;
const walkText = (dir, out = []) => {
  if (!fs.existsSync(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === '.local' || e.name === '.git') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkText(p, out); else if (TEXT_FILE.test(e.name)) out.push(p);
  }
  return out;
};
const textFiles = [...['api', 'app', 'scripts', 'test', 'docs', 'infra', '.github'].flatMap((d) => walkText(path.join(ROOT, d))),
  ...fs.readdirSync(ROOT, { withFileTypes: true }).filter((e) => e.isFile() && TEXT_FILE.test(e.name)).map((e) => path.join(ROOT, e.name))];
for (const file of textFiles) {
  if (RAW_CHARS.test(fs.readFileSync(file, 'utf8'))) fail(`${path.relative(ROOT, file).replace(/\\/g, '/')} contains raw control or invisible characters; write them as escapes`);
}

// 10. app/js has no build step except REGISTERED vendored bundles (BT-011-02; adapted from
//     TaskTracker's checkVendoredFrontend). Each is generated by a committed script from exact pins
//     recorded in its banner, carries its licence notices, and has an npm script to regenerate it.
//     A directory under app/js/vendor that is not registered here fails.
const VENDORED_BUNDLES = [{
  dir: 'tiptap', files: ['tiptap-bundle.js', 'tiptap.css'], script: 'vendor:tiptap', generator: 'scripts/build/vendor-tiptap.mjs',
  packages: ['@tiptap/core', '@tiptap/pm', '@tiptap/starter-kit', '@tiptap/extension-list', 'esbuild'],
}];
const vendorDir = path.join(ROOT, 'app/js/vendor');
if (fs.existsSync(vendorDir)) {
  const rootPkg = json('package.json');
  const declared = { ...(rootPkg.dependencies || {}), ...(rootPkg.devDependencies || {}) };
  const registered = new Set(VENDORED_BUNDLES.map((b) => b.dir));
  for (const e of fs.readdirSync(vendorDir, { withFileTypes: true })) {
    if (!e.isDirectory() || !registered.has(e.name)) fail(`app/js/vendor/${e.name} is not a registered vendored bundle`);
  }
  for (const b of VENDORED_BUNDLES) {
    const dir = path.join(vendorDir, b.dir);
    for (const f of b.files) if (!fs.existsSync(path.join(dir, f))) fail(`app/js/vendor/${b.dir}/${f} is missing; run npm run ${b.script}`);
    if (!fs.existsSync(path.join(ROOT, b.generator))) fail(`${b.generator} is missing, so app/js/vendor/${b.dir} could not be regenerated`);
    if (!rootPkg.scripts || !rootPkg.scripts[b.script]) fail(`package.json has no "${b.script}" script`);
    const entry = path.join(dir, b.files[0]);
    if (!fs.existsSync(entry)) continue;
    const src = fs.readFileSync(entry, 'utf8');
    if (!src.includes('GENERATED FILE') || !src.includes(`npm run ${b.script}`)) fail(`app/js/vendor/${b.dir}/${b.files[0]} has no generated-file banner naming npm run ${b.script}`);
    if (!src.includes('Permission is hereby granted')) fail(`app/js/vendor/${b.dir}/${b.files[0]} is missing its third-party licence notices`);
    for (const name of b.packages) {
      const pin = declared[name];
      if (!pin || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(pin)) fail(`${name} must be pinned to an exact version in package.json (app/js/vendor/${b.dir} is built from it)`);
      else if (!src.includes(`${name}@${pin}`)) fail(`app/js/vendor/${b.dir}/${b.files[0]} was not built from ${name}@${pin}; run npm run ${b.script}`);
    }
  }
}

const ignore = read('.gitignore');
for (const pattern of ['.env', 'local.settings.json', '*.pem', '/backups/', '/exports/', '/receipts/', '/.local/', '*.sqlite']) {
  if (!ignore.split(/\r?\n/).includes(pattern)) fail(`.gitignore no longer contains ${pattern}`);
}

if (errors.length) {
  for (const e of errors) console.error(`validate: ${e}`);
  console.error(`validate: ${errors.length} error(s)`);
  process.exit(1);
}
console.log(`validate: ok (${Object.keys(ROUTES).length} routes)`);
